### ISSUE TITLE
Thank you for breaking Applications

### ISSUE THREAD

**Issue by LKDevelopment** [SSilence/php-imap-client#140]
Hey,

i just want to thank you, that you break Applications that use your Package!

Because of your change (the stuff with the Incoming Message Class) a big application doesn't work anymore, and it isn't possible to jump back to an version that works. Thanks for this!

**Comment by xXXIMMATTHEWXXx** [comment]
Hello! We do _not_ modify any environment variables so this is not possible. Even so it is good practice to use a service like git to make multiple versions of a project,

**Comment by LKDevelopment** [comment]
Sure, but you modified the thing in development before release. Just git tag the stuff, so that it is possible to jump back to an old version, currently it isn't possible because you develop on "dev" & "master" & "2.0" ?

**Comment by xXXIMMATTHEWXXx** [comment]
Old versions cannot be supported and really REALLY should not be used

**Comment by xXXIMMATTHEWXXx** [comment]
General code issues. It worked, but a lot of "WIP" comments and code that does not work was in there. Also, attachments did not work on most servers. Docs were not up to date at the time and generally, the code was bad. Do note that commits is VERY old and the new class structure is must easier, more efficient and supports most servers. In the future, we will make changes to the dev branch. This was not set before and this library basically was rebuilt. We are worried about supporting as much as we can. However, that commit is very old and due to the class structure, we simply cannot support that old class. I recommend that you look through the code and find where you reference our library, read our new docs and recode those bits. Sorry for the inconvenience.

**Comment by LKDevelopment** [comment]
Sure that would be the best solution, but also it would be better if you git-tag the versions,

**Comment by xXXIMMATTHEWXXx** [comment]
Ill be sure to work that in. We are also going to, starting at version 2.0, notify all devs of big API changes,

**Comment by xXXIMMATTHEWXXx** [comment]
You can check the archive folder for now

**Comment by sergey144010** [comment]
You can clone the repository and roll back the changes before the commit that you need. And getMessages() returns an array, but only objects.

**Comment by MSAyrese** [comment]
@sergey144010 @xXXIMMATTHEWXXx 
Thank you for breaking Applications
I updated files and all of my codes give me error.
You Shit in codes. :|

**Comment by sergey144010** [comment]
Which errors?

**Comment by MSAyrese** [comment]
he...
compare a week ago getMessage function with now. all structure changed

**Comment by xXXIMMATTHEWXXx** [comment]
We have solved this issue. Useless ranting that people can barely read is
not needed. I will close this issue asap
