### ISSUE TITLE
getMessages() marks all messages as read.

### ISSUE THREAD

**Issue by abdullahseba** [SSilence/php-imap-client#161]
Hi
`getMessages()` retrieves all the messages and marks them as read.
So on the first run it will return the message as unread before marking it as read.
So while I load this page which uses `getMessages()` I can see the messages been marked as read one by one in outlooks web app.
![image](https://cloud.githubusercontent.com/assets/25548754/25902021/418421d8-3590-11e7-8374-e54334d2ba23.png)
![image](https://cloud.githubusercontent.com/assets/25548754/25902128/8f68ecda-3590-11e7-93b2-8a5698bc18aa.png)

**Comment by techie42** [comment]
The issue is the "imap_fetchbody" call in the "imapFetchbody" function in file "IncomingMessage.php", around line 506.  According to the docs on php.net, FT_PEEK should be added as an option on the call in order to preserve the read status when fetching the message body.  If FT_PEEK is not used, then imap_fetchbody will change the read status to SEEN. 

For example, if I modify the original code to this:

`		return imap_fetchbody($this->imapStream, $this->id, $section, FT_PEEK);`

Then, the issue disappears :)

**Comment by xXXIMMATTHEWXXx** [comment]
Thank you. I will add this as well as a comment so other devs know

**Comment by techie42** [comment]
Thank you very much :) Great response. This library makes life so much easier :)

**Comment by xXXIMMATTHEWXXx** [comment]
Your welcome! I have just commited the update. Let me know if you have any
other problems :)

**Comment by abdullahseba** [comment]
Cant try cuz of #163 :(

**Comment by xXXIMMATTHEWXXx** [comment]
Yes, I am working on this as we speak. I plan to have this fixed by today

**Comment by abdullahseba** [comment]
Yep it works :)

**Comment by xXXIMMATTHEWXXx** [comment]
:)
