### ISSUE TITLE
getMessagesOverview needs to return id

### ISSUE THREAD

**Issue by abdullahseba** [SSilence/php-imap-client#172]
Hi agaiiiiiiiiiiiin 
`getMessagesOverview` needs to return an id as well as `uid` its annoooying having to use `getId` all the time.

**Comment by xXXIMMATTHEWXXx** [comment]
According to our latest code in ImapClient.php, getMessagesOverview and getMessageOverview are basically the same thing. So, all we do it get the provided id and call the imap_fetch_overview. This is what returns the uid according to the docs. In order to call these, you need to have the id. I recommend making a php oop class. Like below
```php

use use SSilence\ImapClient\ImapClient;
class Email {

    protected $id;

    public function __construct($id) {
        $imap = new ImapClient;
        $imap->getMessage($id);
        // Set other info provided by get message to a var of this class
        $this->id = $id;
    }

    public function getId() {
        return $this->id;
    }
}
```
Then use it like so:
```php
$email = new Email(//put id of message here however you get that);

echo $email->getId();

```
